// <auto-generated />
using System;
using GamePatchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamePatchService.Data.Migrations
{
    [DbContext(typeof(GamePatchDbContext))]
    [Migration("20251113220815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamePatchService.Core.Models.DownloadRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatchFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatchFileId");

                    b.HasIndex("Status");

                    b.ToTable("DownloadRecords");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.GameVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber");

                    b.HasIndex("GameId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.PatchFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("FromVersionId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ToVersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToVersionId");

                    b.HasIndex("FromVersionId", "ToVersionId")
                        .IsUnique();

                    b.ToTable("PatchFiles");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.DownloadRecord", b =>
                {
                    b.HasOne("GamePatchService.Core.Models.PatchFile", "PatchFile")
                        .WithMany("Downloads")
                        .HasForeignKey("PatchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatchFile");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.GameVersion", b =>
                {
                    b.HasOne("GamePatchService.Core.Models.Game", "Game")
                        .WithMany("Versions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.PatchFile", b =>
                {
                    b.HasOne("GamePatchService.Core.Models.GameVersion", "FromVersion")
                        .WithMany("PatchesFrom")
                        .HasForeignKey("FromVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamePatchService.Core.Models.GameVersion", "ToVersion")
                        .WithMany("PatchesTo")
                        .HasForeignKey("ToVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromVersion");

                    b.Navigation("ToVersion");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.Game", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.GameVersion", b =>
                {
                    b.Navigation("PatchesFrom");

                    b.Navigation("PatchesTo");
                });

            modelBuilder.Entity("GamePatchService.Core.Models.PatchFile", b =>
                {
                    b.Navigation("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
